### ISSUE TITLE
Github Pages only builds after changes in the branch gh-pages

### ISSUE THREAD

**Issue by daniel-bogdoll** [daniel-bogdoll/ad-datasets#10]
This means, after adding a dataset to data.js, the website is not rebuild automatically.

**Comment by daniel-bogdoll** [comment]
Also I believe something is broken...I have updated several fields (e.g. Argo Motion Forecasting) but they do not appear on the website, even though I have triggered a build process

**Comment by Xirimi90** [comment]
Changes in the main branch are brought to the website via "npm run deploy". However, it takes a couple of minutes until the website is actually updated.

**Comment by daniel-bogdoll** [comment]
Is it possible to change this behaviour so that the automatically triggered github pages [builds](https://github.com/daniel-bogdoll/ad-datasets/deployments/activity_log?environment=github-pages) after each commit can do the job?

**Comment by FelixSchreyer** [comment]
Should be working now
