### ISSUE TITLE
"Rows per page" functionality not working

### ISSUE THREAD

**Issue by daniel-bogdoll** [daniel-bogdoll/ad-datasets#2]
Only the default value "10" is working, selecting "25" or "50" does nothing. Tested on Google Chrome under Windows 10.

**Comment by Xirimi90** [comment]
It appears to only work with Firefox.

**Comment by daniel-bogdoll** [comment]
Here I found some details on the bug: https://github.com/mui-org/material-ui-x/issues/1713

**Comment by Xirimi90** [comment]
Should be working now, tested on Safari

**Comment by daniel-bogdoll** [comment]
Pls test in Chrome, Edge, Firefox, Safari :)

**Comment by daniel-bogdoll** [comment]
Not working at my side again

**Comment by SamyZog** [comment]
Same here, any news on this?
