### ISSUE TITLE
Identical dataset

### ISSUE THREAD

**Issue by daniel-bogdoll** [daniel-bogdoll/ad-datasets#35]
""id": "Playing for Data", and GTA5 are the same, I think GTA5 is the correct name

![image](https://user-images.githubusercontent.com/19552411/167790825-6fa31dcb-0dce-4e34-8479-60b5b3cacf3c.png)

**Comment by Nishanth-Gowda-95** [comment]
Yes, I updated GTA5 and removed the duplicate.
