### ISSUE TITLE
BDD100K License incorrect

### ISSUE THREAD

**Issue by miquelmarti** [daniel-bogdoll/ad-datasets#42]
https://github.com/daniel-bogdoll/ad-datasets/blob/b78e51d733c81b95579ab8322d907be1a0463767/my-app/src/data.json#L221 

According to https://doc.bdd100k.com/license.html, BSD3 clause is for code, data is under a different license available in link.

**Comment by daniel-bogdoll** [comment]
Thanks for spotting this one! I updated it
